mission:
  name: "intercept_moving_target"
  description: "Intercept and capture a moving target in forest environment"
  
objectives:
  primary: "intercept_target"
  secondary: "avoid_obstacles"
  tertiary: "minimize_flight_time"

parameters:
  max_flight_time: 300  # seconds
  intercept_radius: 5.0  # meters
  max_speed: 15.0  # m/s
  altitude_range: [2.0, 50.0]  # min/max altitude in meters
  
target:
  initial_position: [100, 5, 100]
  movement_pattern: "evasive"
  speed_range: [3.0, 8.0]
  
environment:
  terrain_type: "forest"
  obstacle_density: "medium"
  weather: "clear"
  visibility: "good"

constraints:
  no_fly_zones: []
  emergency_landing_sites: [[0, 0, 0], [200, 0, 200]]
  
scoring:
  success_points: 100
  time_bonus_factor: 0.5
  collision_penalty: -25
  distance_efficiency: 1.0 